### PR TITLE
Replace pop-out icon with svg

### PR DESCRIPTION
**Pull request by christopheschwyzer**
screen shot 2015-06-04 at 13 59 25

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
@njam please review

**Comment by njam** [comment]
Looks good!
Did you check this in IE? We had some positioning problems with SVG in IE...

**Comment by christopheschwyzer** [comment]
I see, you're right. I needed to add dimension to the SVG. Works now. 

See also. http://stackoverflow.com/questions/21840551/background-size-with-svg-squished-in-ie9-10

@njam please verify

**Comment by njam** [comment]
thanks, looks good.

Closing in favor of https://github.com/renee-bar/renee-bar.github.io/pull/13 (need to recreate dist/).

**Pull request closed without merging**
