### PR TITLE
Try out snap scrolling

### PR DESCRIPTION
**Pull request by njam**
e.g. https://github.com/alvarotrigo/fullPage.js

### CODE REVIEW

**Comment by njam** [comment]
@christopheschwyzer fyi I pushed some drafts. Seems to work mostly fine.

Problem is that the slide now has a height of "100%", if we have too many concerts the content will be cut off. Not sure how to handle that. Do you have an idea?

**Comment by christopheschwyzer** [comment]
We could
- limit the shown number of venues
- apply snap scroll only for _larger_ screens (enquire)

Or somehow only do it on the first slide...

**Comment by christopheschwyzer** [comment]
About snap scrolling http://blog.gospodarets.com/css-scroll-snap/?utm_source=CSS-Weekly&utm_campaign=Issue-170&utm_medium=email

**Comment by njam** [comment]
Nice!

http://caniuse.com/#feat=css-snappoints
https://www.chromestatus.com/feature/5721832506261504

**Comment by njam** [comment]
I tried with:
```css
html {
  scroll-snap-type: y mandatory;
}
.slide {
  scroll-snap-align: start;
}
```

It's nice for the first slide, which is 100% high. But it doesn't work for the event list, which is higher than 100%, one cannot scroll down to see all the events anymore. The viewport is always scrolled up to the beginning of the list automatically.

Closing as wontfix.

**Pull request closed without merging**
