### PR TITLE
Add icons: madeinbasel, github

### PR DESCRIPTION
**Pull request by christopheschwyzer**
At the bottom of `ul.eventList` in `index.html`?
Or rather a separate `<footer>` element?

@christopheschwyzer maybe something for you?

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
One thing I'm not sure - I extracted `.slide` that is set to 100% of the viewport. For the _agenda_ section it doesn't make much sense currently. (With https://github.com/renee-bar/renee-bar.github.io/issues/8 it will though)

@njam please review

**Comment by njam** [comment]
I think it would be good if the footer was not using *extra space*. When you scroll down on the page I think the "agenda" part should be fully visible (i.e. take one screen height).
How about putting the footer into the last slide?

**Comment by christopheschwyzer** [comment]
I removed `.slide` for now. Guess it's ok for now (without snap scroll). Of course we could wrap _Agenda_ and _Footer_ in a `.slide` div - but then you just have a lot of empty whitespace at the bottom. Not sure how you wanted it ;)

**Comment by njam** [comment]
I meant to keep the "two slides approach", so that one can easily slide from the "splash screen" down to the agenda and back. For the agenda to be easily visible the icons should not use additional space.
i.e.:
screen shot 2015-06-14 at 16 15 53

wdyt?

**Comment by christopheschwyzer** [comment]
Aha I see. Will do it.

**Comment by christopheschwyzer** [comment]
@njam please review

**Comment by njam** [comment]
closing in favor of https://github.com/renee-bar/renee-bar.github.io/pull/16

**Pull request closed without merging**
